{% set name = "QCLSolver" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/Q/QCLSolver/QCLSolver-1.0.3.tar.gz
  sha256: 5e499ec2414e02fe93afe0cc3d6f7f91d6b647f740739fec213c93e32947f19c

build:
  number: 0
  script: "python -m pip install . -vv"

requirements:
  host:
    - numpy >=1.16.5
    - pip
    - python
    - scipy >=1.4.1
  run:
    - numpy >=1.16.5
    - python
    - scipy >=1.4.1

test:
  imports:
    - QCLSolver

about:
  home: https://pypi.org/project/QCLSolver/
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "A tool for cluster expansion solver."
  doc_url: https://github.com/yesunhuang/QCLS/blob/main/README.md
  dev_url: https://github.com/yesunhuang/QCLS

extra:
  recipe-maintainers:
    - leonardodalinky
    - yesunhuang
