{% set name = "QCLSolver" %}
{% set version = "1.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/Q/QCLSolver/QCLSolver-1.0.4.tar.gz
  sha256: 147651b48b248767ff074339d2c418a4fcf03b2974b4363b8dd42a36c63ce973

build:
  number: 0
  script: "python -m pip install . -vv"

requirements:
  host:
    - numpy >=1.16.5
    - pip
    - python
    - scipy >=1.4.1
  run:
    - numpy >=1.16.5
    - python
    - scipy >=1.4.1

test:
  imports:
    - QCLSolver

about:
  home: https://pypi.org/project/QCLSolver/
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "A tool for cluster expansion solver."
  doc_url: https://github.com/yesunhuang/QCLS/blob/main/README.md
  dev_url: https://github.com/yesunhuang/QCLS

extra:
  recipe-maintainers:
    - leonardodalinky
    - yesunhuang
